[tool.poetry]
name = "pyredactkit"
version = "0.1.0"
description = "Python cli tool to redact sensitive data"
authors = ["brootware <brootware@outlook.com>"]
license = "GNU"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.1.2"
regex = "^2022.4.24"
attrs = "^21.4.0"
click = "^8.1.3"
iniconfig = "^1.1.1"
joblib = "^1.1.0"
packaging = "^21.3"
pluggy = "^1.0.0"
py = "^1.11.0"
pyparsing = "^3.0.8"
tomli = "^2.0.1"
tqdm = "^4.64.0"
nltk = {url = "https://files.pythonhosted.org/packages/b4/e0/840a250e5f85c480389c44d4058c7888b0c9f5f5333b353c77782a8a8e23/nltk-3.7.zip"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
